package OOP2.proekt.f22621609.enums;

public enum CommandType {
    CLOSE, EXIT, HELP, OPEN, SAVE, SAVEAS, LIST, PRINT, SAVEAUTO,
    CHECKEMPTY, CHECKDETERMINISTIC, RECOGNIZE, CHECKFINITE,
    UN, REG, CONCAT , UNION
}